version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - ${PORT_GRAFANA}:3000
    restart: unless-stopped

networks:
  default:
    name: jenkins
    external: true
