version: '3'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      default:
        aliases:
          - docker
    ports:
      - 2376:2376
    command: --storage-driver overlay2
    restart: unless-stopped

  jenkins-blueocean:
    image: myjenkins-blueocean:2.387.2-1
    container_name: jenkins-blueocean
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT_JENKINS}:8080
      # - 50000:50000
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on: 
      - jenkins-docker

networks:
  default:
    name: jenkins
    external: true

volumes:
  jenkins-docker-certs:
  jenkins-data:
