#!/bin/bash

# Load .env file
set -o allexport
if [ ! -f .env ]; then
	source format.env
else
	source .env
fi
set +o allexport

# Set jenkins url
if [ ! -z "$URL_JENKINS" ]
then
	echo '
	# Generated by Rozikin Script
	server {
        server_name '"$URL_JENKINS"';
		listen 80;
        location / {
                proxy_ssl_server_name on;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://127.0.0.1:'"$PORT_JENKINS"'/;
        }
	}
	' | sudo tee /etc/nginx/sites-available/$PORT_JENKINS.$URL_JENKINS
	sudo ln -s /etc/nginx/sites-available/$PORT_JENKINS.$URL_JENKINS /etc/nginx/sites-enabled/$PORT_JENKINS.$URL_JENKINS 
	sudo systemctl restart nginx
	sudo certbot --nginx -d $URL_JENKINS

	echo "--------------------------------------------------------------"
	echo "Your Jenkins now accessible on: https://"$URL_JENKINS
	echo "--------------------------------------------------------------"
	# Sleep 10 second to next process
	echo "Sleep 10 second to the next process"
	sleep 10s
fi

# Set promotheus url
if [ ! -z "$URL_PROMOTHEUS" ]
then
	echo '
	# Generated by Rozikin Script
	server {
        server_name '"$URL_PROMOTHEUS"';
		listen 80;
        location / {
                proxy_ssl_server_name on;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://127.0.0.1:'"$PORT_PROMOTHEUS"'/;
        }
	}
	' | sudo tee /etc/nginx/sites-available/$PORT_PROMOTHEUS.$URL_PROMOTHEUS
	sudo ln -s /etc/nginx/sites-available/$PORT_PROMOTHEUS.$URL_PROMOTHEUS /etc/nginx/sites-enabled/$PORT_PROMOTHEUS.$URL_PROMOTHEUS 
	sudo systemctl restart nginx
	sudo certbot --nginx -d $URL_PROMOTHEUS

	echo "--------------------------------------------------------------"
	echo "Your Promotheus now accessible on: https://"$URL_PROMOTHEUS
	echo "--------------------------------------------------------------"
	# Sleep 10 second to next process
	echo "Sleep 10 second to the next process"
	sleep 10s
fi

# Set grafana url
if [ ! -z "$URL_GRAFANA" ]
then
	echo '
	# Generated by Rozikin Script
	server {
        server_name '"$URL_GRAFANA"';
		listen 80;
        location / {
                proxy_ssl_server_name on;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://127.0.0.1:'"$PORT_GRAFANA"'/;
        }
	}
	' | sudo tee /etc/nginx/sites-available/$PORT_GRAFANA.$URL_GRAFANA
	sudo ln -s /etc/nginx/sites-available/$PORT_GRAFANA.$URL_GRAFANA /etc/nginx/sites-enabled/$PORT_GRAFANA.$URL_GRAFANA 
	sudo systemctl restart nginx
	sudo certbot --nginx -d $URL_GRAFANA

	echo "--------------------------------------------------------------"
	echo "Your Grafana now accessible on: https://"$URL_GRAFANA
	echo "--------------------------------------------------------------"
	# Sleep 10 second to next process
	echo "Sleep 10 second to the next process"
	sleep 10s
fi
